# Generated by Django 3.1.4 on 2020-12-26 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedDev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_id', models.CharField(default='', max_length=100)),
                ('twitter_username', models.CharField(default='', max_length=100)),
                ('github_id', models.CharField(default='', max_length=100)),
                ('github_username', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RequestRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField()),
                ('connected', models.BooleanField()),
                ('common_organizations', models.TextField(default='[]', max_length=100)),
                ('dev_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev_1', to='connections.connecteddev')),
                ('dev_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev_2', to='connections.connecteddev')),
            ],
        ),
    ]
